---

- hosts: localhost
  gather_facts: true
  connection: local
  # become: true
  vars:
    component: '{{component}}'
  roles:
    - { role: setup }
    - { role: postgres }
  tags: [setup, postgres] 
